CONFIG_IMAGES_DIR = "./Images/";
CONFIG_SCENES_DIR = "./Scenes/";
CONFIG_LIBRARY_FILES_DIR = "./LibraryFiles/";
CONFIG_CHARS_DIR = "./Chars/";

///////////////////////////
// DO NOT MODIFY
///////////////////////////
CONFIG_STAGES_DIR = CONFIG_IMAGES_DIR + CONFIG_SCENES_DIR;
CONFIG_CHARS_FULL_DIR = CONFIG_IMAGES_DIR + CONFIG_CHARS_DIR;
CONFIG_LOGGING_VERBOSE = false;